name: projek_skripsi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_image_compress: ^1.1.3
  cached_network_image: ^3.2.3
  get: ^4.6.5
  qr_code_scanner: ^1.0.1
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  syncfusion_flutter_sliders: ^25.1.37
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  lottie: 1.2.2
  email_validator: ^2.1.17
  cloud_firestore: ^4.14.0
  encrypt: ^5.0.3
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  internet_connection_checker_plus: ^2.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.0.1
  googleapis_auth: ^1.4.0
  http: ^1.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  screenshot: ^3.0.0
  uuid: ^4.4.0
  dcdg: ^4.1.0
  audioplayers: ^5.2.1
  flutter_launcher_icons: "0.12.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/data/
    - assets/vector/
    - assets/photo/
    - assets/lottie/
    - assets/sfx/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
